### ISSUE TITLE
Загрузка конфигурации из исходников невозможна

### ISSUE THREAD

**Issue by Merkalov** [zeltyr/1c_platforma_spec#7]
![Screenshot_17](https://github.com/zeltyr/1c_platforma_spec/assets/28949451/8a6b373a-85bb-47e1-af14-0481e4b6a820)
"Конфигурация -> Загрузить конфигурацию из файлов" выдает ошибку. Пробовал 5-6 билет.

**Comment by zeltyr** [comment]
Такое может быть, я тогда только начинал знакомство с загрузкой и выгрузкой файлов. К сожалению из-за текущей нагрузки я не смогу поддерживать этот репозиторий в актуальном состоянии и исправлять ошибки.
